kind: pipeline
type: docker
name: droneTest-svc

steps:
  # - name: check
  #   commands:
  #   - docker images
  
  - name: build
    image: base-python-image:python3.10-with-pipenv
    commands:
      # - docker-compose -f docker-compose.yml up -d --build
      - cd /app && pwd
      - pip install -r requirements.txt
      - uvicorn app:app --host 0.0.0.0 --port 28080