kind: pipeline
type: docker
name: droneTest-svc

steps:
  - name: check
    commands:
    - docker images
  
  - name: build
    # image: docker
    commands:
      - docker-compose -f docker-compose.yml up -d --build